version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      #- "--log.level=DEBUG"
      # API
      - "--api=false"
      - "--api.insecure=true"
      - "--api.debug=false"
      - "traefik.http.routers.api.rule=Host(`traefik.muhsyahrul.my.id`)" # DOMAIN SETTING
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      # DASHBOARD
      - "--api.dashboard=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.muhsyahrul.my.id`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # MIDDLEWARE
      - "traefik.http.middlewares.auth.basicauth.usersfile=/basicauth/users"
      # PROVIDERS
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # ENTRYPOINT
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # SSL
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=msyahrul801@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # SSL certificate verification methods
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # TLS challenge
      # - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web" # TLS http challenge
    volumes:
      - "./auth:/basicauth/users"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
