version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      #- "--log.level=DEBUG"
      # SETTINGS
      - "--api=true"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--api.debug=false"
      # PROVIDERS
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # ENTRYPOINT
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # SSL
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # SSL certificate verification methods
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # TLS challenge
      # - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web" # TLS http challenge
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/users"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN_DASHBOARD}`)" # DOMAIN SETTING
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    volumes:
      - "./auth:/auth"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
